language: node_js
node_js:
  - 14

branches:
  only:
    - main

services: docker

before_install:
  - docker login -u janus1221 -p wlgns7124!
  - docker build -t janus1221/next-test-3 -f Dockerfile .
  - docker push janus1221/next-test-3

notifications:
  email:
    recipients:
      - janus7359@gmail.com